<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <title><?= $title ?></title>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/<?= $style ?>.css">
  <script type="text/javascript" src="js/jquery-2.1.0.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
</head>
<body>
  <div id="header-wrap">
    <div class="center-wrap">
      <h1>
        <a href="/">知乎箱底</a>
      </h1>
      <form id="SearchForm">
        <div class="row">
          <div class="col-md-8">
            <input placeholder="搜索问题" type="text" name="kw" class="form-control" value="<?= $kw ?>">
          </div>
          <div class="col-md-2">
            <button class="btn btn-<?= $style == 'red' ? 'danger' : 'primary' ?> ">搜索</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="">
    <div class="center-wrap">
      <?php foreach ($answers as $key => $answer): ?>
      <div class="question-item">
        <div class="question">
          <a href="http://www.zhihu.com/question/<?= $answer->q_id ?>" target="_blank" class=" external"><?= htmlspecialchars($answer->title) ?></a>
        </div>
        <a href="http://www.zhihu.com/people/<?= $answer->user ?>" class="avatar">
          <img src="<?= $answer->avatar ?>">
        </a>
        <a href="http://www.zhihu.com/people/<?= $answer->user ?>" target="_blank" class="name"><?= htmlspecialchars($answer->nick_name) ?></a>
        <div class="summary">
          <?= mb_strimwidth(strip_tags($answer->text), 0, 128, '...', 'utf8'); ?>
          <a target="_blank" href="http://www.zhihu.com/question/<?= $answer->q_id ?>/answer/<?= $answer->aid ?>" class="more-btn">查看详细</a>
        </div>
      </div>
      <?php endforeach ?>
    </div>
  </div>
  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script>
  $("img").each(function(){$(this).attr("src",$(this).attr("data-actualsrc"))});
  </script>

</body>
</html>
