<!DOCTYPE HTML>
<html>
<head>
  <title><?= $title ?></title>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <style type="text/css">
  body {
  }
  #header-wrap {
    height: 46px;
    background-color: #CB3E3E;
    border-bottom: 1px solid #9C4747;
    box-shadow: 0 1px 2px rgba(0,0,0,.25), inset 0 1px 0 rgba(255,255,255,.15);
  }
  #header-wrap h1 {
    margin: 0;
    font-size: 30px;
    width: 147px;
    float: left;
    color: #fff;
  }
  #SearchForm {
    float: left;
  }
  #SearchForm .row {
    width: 600px;
    margin-top: 6px;
  }
  #SearchForm * {
    float: left;
    display: block;
  }
  .center-wrap {
    width: 950px;
    margin: auto;
  }

  .question-item {
    width: 640px;
    border-top: 1px solid #aaa;
    margin-top: 15px;
    margin-bottom: 15px;
    padding-top: 5px;
    font-size: 13px;
  }
  .question {
    display: block;
    font-size: 14px;
    line-height: 25px;
    font-weight: bold;
  }
  .avatar {
    float: left;
    border-radius: 3px;
    margin-left: 3px;
  }
  .avatar img {
    width: 50px;
    height: 50px;
  }
  .name {
    display: block;
    margin-left: 61px;
    font-weight: bold;
    color: #222;
  }
  .summary {
    margin-left: 61px;
  }

  </style>
  <script type="text/javascript" src="js/jquery-2.1.0.min.js"></script>
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
</head>
<body>
  <div id="header-wrap">
    <div class="center-wrap">
      <h1>知乎箱底</h1>
      <form id="SearchForm">
        <div class="row">
          <div class="col-md-8">
            <input placeholder="搜索问题" type="text" name="kw" class="form-control">
          </div>
          <div class="col-md-2">
            <button class="btn btn-danger">搜索</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="">
    <div class="center-wrap">
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫能用暴力、威胁、威迫威迫威迫威迫威迫的规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
      <div class="question-item">
        <a href="" class="question">为什么刘姥姥这样的穷亲戚在大观园受到王熙凤的款待？</a>
        <a href="" class="avatar"><img src="http://p2.zhimg.com/5e/4c/5e4ce4ac0_m.jpg"></a>
        <a href="" class="name">朱怡婧</a>
        <div class="summary">
          我接触的性工作者的情况和另一位匿名用户相反，大多数都是自愿的。 我们的时代不算很好，但是也不大可能用暴力、威胁、威迫的手段大规模、长期、...
          <a href="" class="more-btn">查看详细</a>
        </div>
      </div>
    </div>
  </div>

</body>
</html>
